### ISSUE TITLE
doh-server container turns unhealthy when loopback address is used as upstream DNS server

### ISSUE THREAD

**Issue by J-Siu** [satishweb/docker-doh#1] opened 2020-08-25 14:54 UTC
I use your image to setup a doh front end, compose as follow:

```yml
  doh-server:
    restart: unless-stopped
    logging:
      options:
        tag: "{{.Name}}"
    image: satishweb/doh-server
    container_name: doh-server
    hostname: doh-server
    network_mode: host
    environment:
      DEBUG: "0"
      UPSTREAM_DNS_SERVER: "udp:127.0.0.53:53"
      DOH_HTTP_PREFIX: "/resolve"
      DOH_SERVER_LISTEN: "[::1]:8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
```

However I notice it will turn unhealthy in a few minutes(no traffic/load required):

```sh
$ docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                      PORTS                                       NAMES
adbab228d04b        satishweb/doh-server   "/docker-entrypoint …"   17 minutes ago      Up 17 minutes (unhealthy)                                               doh-server
```

I tried `DOH_SERVER_VERBOSE: "ture"` but there is no extra message at all. Tried on 2 different linux box.

**Comment by thomasreiser** [comment] 2020-09-17 14:34
Same for me. My way to start the doh server:

```
docker run --name doh -d --restart=always \
 --env "UPSTREAM_DNS_SERVER=udp:127.0.0.1:53" \
 --env "VIRTUAL_HOST=XXXXX.tld" \
 --env "VIRTUAL_PORT=8053" \
 --env "LETSENCRYPT_HOST=XXXXX.tld" \
 satishweb/doh-server
```

**Comment by satishweb** [comment] 2020-12-26 04:54
Hi @thomasreiser @J-Siu 

Technically, using loopback address as DNS upstream should work, however, I noticed that the current version of doh-server does not work as expected with it.

I did few tests using `"UPSTREAM_DNS_SERVER=udp:127.0.0.1:53"` and below were the observations:
1.  `doh-server` daemon was failing to resolve DNS names using loopback address as upstream DNS server inside the container. This caused fail responses to all incoming HTTP requests for DNS resolution.
2.  `doh-server` daemon was not printing failure logs even though verbose mode was turned on in the configuration file. 
3.  Using any working DNS server address other than the loopback address worked as expected.
4.  When the public DNS server was used as an upstream DNS server, the doh-server was printing success logs with verbose mode turned on.

I am creating an issue in [DOH Server source](https://github.com/m13253/dns-over-https) and hopefully, we will have some answers/fixes for the above observations.

### To fix this issue, we have two options at this moment:
**Option 1:** Run unbound DNS server using docker image as `unbound` service and set `UPSTREAM_DNS_SERVER` variable value to `udp:unbound:53` in `doh-server` service configuration. Example configuration is available here -> [Docker Compose Example](https://github.com/satishweb/docker-doh/blob/master/examples/docker-compose-doh-server/docker-compose.yml) 
Note: Unbound DNS server docker image comes with auto-blocking of bad DNS hosts and ads, for more details, please click [here](https://github.com/StevenBlack/hosts)

**Option 2:** Use public DNS servers such as `8.8.8.8`. In this case, `UPSTREAM_DNS_SERVER` variable value should be set to `udp:8.8.8.8:53`. A list of few popular public DNS servers can be found here -> [Public DNS Servers](https://www.techradar.com/news/best-dns-server)

I have updated the README documentation to add more information about `UPSTREAM_DNS_SERVER` variable use. I have set the OpenDNS DNS server address as the default value.

If you are looking to setup local secure DNS server + DOH server then this [Docker Compose Example](https://github.com/satishweb/docker-doh/blob/master/examples/docker-compose-doh-server/docker-compose.yml) could be  helpful.

Thank you for your contribution!

**Comment by satishweb** [comment] 2020-12-26 05:00
Note that @Sm0ke0ut 's health check fix solves the issue around evaluation of variable in health check command. The underlying issue of `doh-server` failing to resolve DNS records using loopback address as upstream DNS server needs further tests and/or fix in [doh-server](https://github.com/m13253/dns-over-https) code.

**Comment by satishweb** [comment] 2020-12-26 05:37
Update: `doh-server` does print error messages on console when it can not reach the upstream server for DNS resolution.

**Comment by satishweb** [comment] 2020-12-26 05:51
New issue is created in `dns-over-https` project: https://github.com/m13253/dns-over-https/issues/95

**Comment by satishweb** [comment] 2021-06-02 01:55
Workaround solution: use `tcp:127.0.0.53:53` as upstream provider.

**Comment by satishweb** [comment] 2021-06-04 21:27
I am going to mark this issue as resolved for now. New version of doh seems to have fixed it.

**Comment by J-Siu** [comment] 2021-06-04 23:22
Can you push a new image to docker hub?

**Comment by satishweb** [comment] 2021-06-05 00:47
With current image build process, I have to wait until new version of stable doh binary is released to create new latest image. I am following a practice of keeping latest image tied to current stable release. I believe this is required as most of the users end up using latest tag.

However, I have a plan to create a "main" tag that uses latest doh binary built on main (master) branch. This shall be done as part of the deploy workflow that I am currently working on. This work should be able to create new image on each merge into main branch.

Until I finish the aforementioned workflow, please continue to use the alternative solution. I will update this ticket when its done. As a temporary solution, If you want to use latest doh binary built from main branch now, you could compile it and use volume map to mount it inside the container.

**Comment by satishweb** [comment] 2021-06-05 00:48
Note: I am marking this as wontfix because the fix is not with the container image creation process

**Comment by satishweb** [comment] 2021-06-05 00:53
Reopening this until we have a new image as new release or new tag

**Comment by KyleKaniecki** [comment] 2021-09-23 17:36
@satishweb Can we release a new docker hub version of this now? 

https://github.com/m13253/dns-over-https/releases/tag/v2.3.0

**Comment by satishweb** [comment] 2021-09-23 22:25
@KyleKaniecki Yes, I will be doing that today

**Comment by satishweb** [comment] 2021-09-24 02:46
@KyleKaniecki New images created and tested. Please try it out and let me know if all is working as expected.

**Comment by satishweb** [comment] 2021-09-24 02:47
@J-Siu We have new images available now, could you please try them out and see if this issue is resolved?

**Comment by J-Siu** [comment] 2021-10-02 20:55
> @J-Siu We have new images available now, could you please try them out and see if this issue is resolved?

I just updated and still showing unhealthy.

**Comment by satish-peloton** [comment] 2021-10-03 05:31
Thanks for testing the latest version. It appears that I need to spend more time to debug and find the root cause. Hopefully, alternative solutions are good enough.

**Comment by satish-peloton** [comment] 2021-10-03 05:41
@J-Siu Using the loopback IP for the DOH server means that DOH is trying to access port 53 on the loopback address inside the container. That will definitely not work unless the same container is running a DNS server or you are using the `host` network for the container.

I will do some tests around this as time permits and let you know if there are any better alternatives/workaround.

**Closed** 2021-10-06 06:43 UTC
Labels: wontfix

**Comment by J-Siu** [comment] 2021-10-07 00:12
> @J-Siu Using the loopback IP for the DOH server means that DOH is trying to access port 53 on the loopback address inside the container. That will definitely not work unless the container is running a DNS server or you are using the `host` network for the container.
> 
> I will do some tests around this as time permits and let you know if there are any better alternatives/workaround.

I am using host network.

```
  doh-server:
    restart: unless-stopped
    logging:
      options:
        tag: "{{.Name}}"
    image: satishweb/doh-server
    container_name: doh-server
    hostname: doh-server
    network_mode: host
    environment:
      DEBUG: "0"
      UPSTREAM_DNS_SERVER: "tcp:127.0.0.53:53"
      DOH_HTTP_PREFIX: "/resolve"
      DOH_SERVER_LISTEN: "[::1]:8053"
      DOH_SERVER_TIMEOUT: "10"
      DOH_SERVER_TRIES: "3"
      DOH_SERVER_VERBOSE: "false"
```
The instant show unhealthy, but it still function though.
